export const offers = [
  {id:'revenue-recovery',name:'Revenue Recovery Team',category:'Sales',headline:'Find the deals that need attention before the forecast meeting.',buyer:'B2B sales and revenue teams',workflowHints:['pipeline','deal','revenue','forecast','quote'],required:['HubSpot','Gmail'],optional:['Salesforce','Calendar','Slack'],setup:'$2,500',monthly:'$299',pilotDays:10,kpis:['Stage aging','Forecast evidence coverage','Next-step completion'],guardrails:['Never fabricate buyer intent','Never send external messages without approval','Never alter commercial terms automatically']},
  {id:'customer-retention',name:'Customer Retention Team',category:'Customer Success',headline:'Surface churn risk while there is still time to intervene.',buyer:'Customer success and support teams',workflowHints:['churn','renewal','customer','support','onboarding'],required:['Intercom','Product analytics'],optional:['Zendesk','HubSpot','Gmail','Slack'],setup:'$2,500',monthly:'$299',pilotDays:10,kpis:['Time to first risk detection','Onboarding completion','Promise closure'],guardrails:['Use minimum necessary customer data','Keep customer communications reviewable','Do not overstate value delivered']},
  {id:'founder-command',name:'Founder Command Team',category:'Operations',headline:'Turn scattered company signals into one decision-ready operating brief.',buyer:'Founders and chiefs of staff',workflowHints:['founder','owner','weekly','decision','inbox','command'],required:['Gmail','Calendar'],optional:['Slack','Notion','Stripe','GitHub'],setup:'$1,500',monthly:'$199',pilotDays:7,kpis:['Decision cycle time','Commitment completion','Owner coverage'],guardrails:['Never invent traction or financial data','Separate evidence from inference','Require a named owner before action']},
  {id:'release-confidence',name:'Release Confidence Team',category:'Engineering',headline:'Ship with dependency, test, rollout, and rollback evidence.',buyer:'Engineering and product teams',workflowHints:['release','incident','schema','dependency','quality','deploy'],required:['GitHub','Issue tracker'],optional:['Linear','Jira','Sentry','Slack'],setup:'$3,500',monthly:'$399',pilotDays:14,kpis:['Change failure rate','Regression escape rate','Mean time to recovery'],guardrails:['No unsupported completion claims','High-impact releases require approval','Keep rollback criteria explicit']},
  {id:'finance-control',name:'Finance Control Team',category:'Finance',headline:'Protect cash and margin with explicit assumptions and approval gates.',buyer:'Finance and procurement teams',workflowHints:['cash','spend','invoice','vendor','margin','finance'],required:['Accounting','Payments'],optional:['Stripe','Drive','Slack'],setup:'$3,500',monthly:'$399',pilotDays:14,kpis:['Cash recovered','Spend exceptions resolved','Forecast variance'],guardrails:['No autonomous money movement','State model assumptions explicitly','Require approval for financial commitments']},
  {id:'growth-intelligence',name:'Growth Intelligence Team',category:'Marketing',headline:'Find evidence-backed growth opportunities without content spam.',buyer:'Marketing and growth teams',workflowHints:['marketing','content','campaign','seo','brand','growth'],required:['Analytics','CMS'],optional:['HubSpot','Social','Email'],setup:'$2,500',monthly:'$299',pilotDays:10,kpis:['Qualified opportunities','Content cycle time','Evidence coverage'],guardrails:['Do not invent market claims','Preserve brand review','Respect channel and consent policies']},
  {id:'people-operations',name:'People Operations Team',category:'People',headline:'Keep hiring, onboarding, role clarity, and handoffs accountable.',buyer:'People and recruiting teams',workflowHints:['recruit','candidate','onboarding','employee','role','people'],required:['ATS or HRIS','Calendar'],optional:['Gmail','Slack','Drive'],setup:'$2,500',monthly:'$299',pilotDays:14,kpis:['Onboarding completion','Time to decision','Handoff coverage'],guardrails:['No autonomous employment decisions','Minimize sensitive data','Require qualified human review']},
  {id:'agency-delivery',name:'Agency Delivery Team',category:'Professional Services',headline:'Protect scope, delivery quality, client promises, and margin.',buyer:'Agencies and professional-services teams',workflowHints:['client','scope','project','agency','delivery','service'],required:['Project tracker','Email'],optional:['Notion','Slack','Accounting'],setup:'$2,500',monthly:'$299',pilotDays:10,kpis:['Scope variance','On-time delivery','Promise closure'],guardrails:['Do not change scope automatically','Keep client-facing messages reviewable','Preserve contractual approval boundaries']}
];

export function recommendOffers(input='') {
  const terms=String(input).toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);
  return offers.map(o=>{
    const hay=[o.name,o.category,o.headline,o.buyer,...o.workflowHints].join(' ').toLowerCase();
    const matches=terms.filter(t=>t.length>2&&hay.includes(t));
    return {...o,matchScore:Math.min(99,55+matches.length*9),matchReasons:matches.slice(0,4)};
  }).sort((a,b)=>b.matchScore-a.matchScore).slice(0,3);
}
